-- Update reviews_public view to include compensation fields
CREATE OR REPLACE VIEW public.reviews_public
WITH (security_invoker=on) AS
SELECT 
  id,
  company_id,
  title,
  pros,
  cons,
  advice,
  rating,
  role_title,
  role_level,
  department,
  tenure_range,
  employment_status,
  employment_type,
  recommend_to_friend,
  ceo_approval,
  helpful_count,
  salary_range,
  market_alignment,
  pay_transparency,
  did_interview,
  interview_experience_rating,
  interview_count,
  interview_difficulty,
  interview_description,
  interview_tips,
  age_range,
  gender,
  ethnicity,
  education_level,
  created_at,
  updated_at,
  -- NEW: Compensation fields for salary display
  base_salary_amount,
  base_salary_currency,
  is_net_salary,
  allowances_amount,
  allowances_currency,
  bonus_amount,
  bonus_currency
FROM public.reviews
WHERE moderation_status = 'approved';