export interface CurrencyInfo {
  code: string;
  name: string;
  flag: string;
}

export const CURRENCIES: CurrencyInfo[] = [
  { code: "AED", name: "UAE dirham", flag: "🇦🇪" },
  { code: "AFN", name: "Afghan afghani", flag: "🇦🇫" },
  { code: "ALL", name: "Albanian lek", flag: "🇦🇱" },
  { code: "AMD", name: "Armenian dram", flag: "🇦🇲" },
  { code: "ANG", name: "Netherlands Antillean guilder", flag: "🇨🇼" },
  { code: "AOA", name: "Angolan kwanza", flag: "🇦🇴" },
  { code: "ARS", name: "Argentine peso", flag: "🇦🇷" },
  { code: "AUD", name: "Australian dollar", flag: "🇦🇺" },
  { code: "AWG", name: "Aruban florin", flag: "🇦🇼" },
  { code: "AZN", name: "Azerbaijani manat", flag: "🇦🇿" },
  { code: "BAM", name: "Bosnia and Herzegovina convertible mark", flag: "🇧🇦" },
  { code: "BBD", name: "Barbadian dollar", flag: "🇧🇧" },
  { code: "BDT", name: "Bangladeshi taka", flag: "🇧🇩" },
  { code: "BGN", name: "Bulgarian lev", flag: "🇧🇬" },
  { code: "BHD", name: "Bahraini dinar", flag: "🇧🇭" },
  { code: "BIF", name: "Burundian franc", flag: "🇧🇮" },
  { code: "BMD", name: "Bermudian dollar", flag: "🇧🇲" },
  { code: "BND", name: "Brunei dollar", flag: "🇧🇳" },
  { code: "BOB", name: "Bolivian boliviano", flag: "🇧🇴" },
  { code: "BRL", name: "Brazilian real", flag: "🇧🇷" },
  { code: "BSD", name: "Bahamian dollar", flag: "🇧🇸" },
  { code: "BTN", name: "Bhutanese ngultrum", flag: "🇧🇹" },
  { code: "BWP", name: "Botswana pula", flag: "🇧🇼" },
  { code: "BYN", name: "Belarusian ruble", flag: "🇧🇾" },
  { code: "BZD", name: "Belize dollar", flag: "🇧🇿" },
  { code: "CAD", name: "Canadian dollar", flag: "🇨🇦" },
  { code: "CDF", name: "Congolese franc", flag: "🇨🇩" },
  { code: "CHF", name: "Swiss franc", flag: "🇨🇭" },
  { code: "CLP", name: "Chilean peso", flag: "🇨🇱" },
  { code: "CNY", name: "Chinese yuan", flag: "🇨🇳" },
  { code: "COP", name: "Colombian peso", flag: "🇨🇴" },
  { code: "CRC", name: "Costa Rican colón", flag: "🇨🇷" },
  { code: "CUP", name: "Cuban peso", flag: "🇨🇺" },
  { code: "CVE", name: "Cape Verdean escudo", flag: "🇨🇻" },
  { code: "CZK", name: "Czech koruna", flag: "🇨🇿" },
  { code: "DJF", name: "Djiboutian franc", flag: "🇩🇯" },
  { code: "DKK", name: "Danish krone", flag: "🇩🇰" },
  { code: "DOP", name: "Dominican peso", flag: "🇩🇴" },
  { code: "DZD", name: "Algerian dinar", flag: "🇩🇿" },
  { code: "EGP", name: "Egyptian pound", flag: "🇪🇬" },
  { code: "ERN", name: "Eritrean nakfa", flag: "🇪🇷" },
  { code: "ETB", name: "Ethiopian birr", flag: "🇪🇹" },
  { code: "EUR", name: "Euro", flag: "🇪🇺" },
  { code: "FJD", name: "Fijian dollar", flag: "🇫🇯" },
  { code: "FKP", name: "Falkland Islands pound", flag: "🇫🇰" },
  { code: "GBP", name: "British pound", flag: "🇬🇧" },
  { code: "GEL", name: "Georgian lari", flag: "🇬🇪" },
  { code: "GHS", name: "Ghanaian cedi", flag: "🇬🇭" },
  { code: "GIP", name: "Gibraltar pound", flag: "🇬🇮" },
  { code: "GMD", name: "Gambian dalasi", flag: "🇬🇲" },
  { code: "GNF", name: "Guinean franc", flag: "🇬🇳" },
  { code: "GTQ", name: "Guatemalan quetzal", flag: "🇬🇹" },
  { code: "GYD", name: "Guyanese dollar", flag: "🇬🇾" },
  { code: "HKD", name: "Hong Kong dollar", flag: "🇭🇰" },
  { code: "HNL", name: "Honduran lempira", flag: "🇭🇳" },
  { code: "HRK", name: "Croatian kuna", flag: "🇭🇷" },
  { code: "HTG", name: "Haitian gourde", flag: "🇭🇹" },
  { code: "HUF", name: "Hungarian forint", flag: "🇭🇺" },
  { code: "IDR", name: "Indonesian rupiah", flag: "🇮🇩" },
  { code: "ILS", name: "Israeli new shekel", flag: "🇮🇱" },
  { code: "INR", name: "Indian rupee", flag: "🇮🇳" },
  { code: "IQD", name: "Iraqi dinar", flag: "🇮🇶" },
  { code: "IRR", name: "Iranian rial", flag: "🇮🇷" },
  { code: "ISK", name: "Icelandic króna", flag: "🇮🇸" },
  { code: "JMD", name: "Jamaican dollar", flag: "🇯🇲" },
  { code: "JOD", name: "Jordanian dinar", flag: "🇯🇴" },
  { code: "JPY", name: "Japanese yen", flag: "🇯🇵" },
  { code: "KES", name: "Kenyan shilling", flag: "🇰🇪" },
  { code: "KGS", name: "Kyrgyzstani som", flag: "🇰🇬" },
  { code: "KHR", name: "Cambodian riel", flag: "🇰🇭" },
  { code: "KMF", name: "Comorian franc", flag: "🇰🇲" },
  { code: "KRW", name: "South Korean won", flag: "🇰🇷" },
  { code: "KWD", name: "Kuwaiti dinar", flag: "🇰🇼" },
  { code: "KYD", name: "Cayman Islands dollar", flag: "🇰🇾" },
  { code: "KZT", name: "Kazakhstani tenge", flag: "🇰🇿" },
  { code: "LAK", name: "Lao kip", flag: "🇱🇦" },
  { code: "LBP", name: "Lebanese pound", flag: "🇱🇧" },
  { code: "LKR", name: "Sri Lankan rupee", flag: "🇱🇰" },
  { code: "LRD", name: "Liberian dollar", flag: "🇱🇷" },
  { code: "LSL", name: "Lesotho loti", flag: "🇱🇸" },
  { code: "LYD", name: "Libyan dinar", flag: "🇱🇾" },
  { code: "MAD", name: "Moroccan dirham", flag: "🇲🇦" },
  { code: "MDL", name: "Moldovan leu", flag: "🇲🇩" },
  { code: "MGA", name: "Malagasy ariary", flag: "🇲🇬" },
  { code: "MKD", name: "Macedonian denar", flag: "🇲🇰" },
  { code: "MMK", name: "Myanmar kyat", flag: "🇲🇲" },
  { code: "MNT", name: "Mongolian tögrög", flag: "🇲🇳" },
  { code: "MOP", name: "Macanese pataca", flag: "🇲🇴" },
  { code: "MRU", name: "Mauritanian ouguiya", flag: "🇲🇷" },
  { code: "MUR", name: "Mauritian rupee", flag: "🇲🇺" },
  { code: "MVR", name: "Maldivian rufiyaa", flag: "🇲🇻" },
  { code: "MWK", name: "Malawian kwacha", flag: "🇲🇼" },
  { code: "MXN", name: "Mexican peso", flag: "🇲🇽" },
  { code: "MYR", name: "Malaysian ringgit", flag: "🇲🇾" },
  { code: "MZN", name: "Mozambican metical", flag: "🇲🇿" },
  { code: "NAD", name: "Namibian dollar", flag: "🇳🇦" },
  { code: "NGN", name: "Nigerian naira", flag: "🇳🇬" },
  { code: "NIO", name: "Nicaraguan córdoba", flag: "🇳🇮" },
  { code: "NOK", name: "Norwegian krone", flag: "🇳🇴" },
  { code: "NPR", name: "Nepalese rupee", flag: "🇳🇵" },
  { code: "NZD", name: "New Zealand dollar", flag: "🇳🇿" },
  { code: "OMR", name: "Omani rial", flag: "🇴🇲" },
  { code: "PAB", name: "Panamanian balboa", flag: "🇵🇦" },
  { code: "PEN", name: "Peruvian sol", flag: "🇵🇪" },
  { code: "PGK", name: "Papua New Guinean kina", flag: "🇵🇬" },
  { code: "PHP", name: "Philippine peso", flag: "🇵🇭" },
  { code: "PKR", name: "Pakistani rupee", flag: "🇵🇰" },
  { code: "PLN", name: "Polish złoty", flag: "🇵🇱" },
  { code: "PYG", name: "Paraguayan guaraní", flag: "🇵🇾" },
  { code: "QAR", name: "Qatari riyal", flag: "🇶🇦" },
  { code: "RON", name: "Romanian leu", flag: "🇷🇴" },
  { code: "RSD", name: "Serbian dinar", flag: "🇷🇸" },
  { code: "RUB", name: "Russian ruble", flag: "🇷🇺" },
  { code: "RWF", name: "Rwandan franc", flag: "🇷🇼" },
  { code: "SAR", name: "Saudi riyal", flag: "🇸🇦" },
  { code: "SBD", name: "Solomon Islands dollar", flag: "🇸🇧" },
  { code: "SCR", name: "Seychellois rupee", flag: "🇸🇨" },
  { code: "SDG", name: "Sudanese pound", flag: "🇸🇩" },
  { code: "SEK", name: "Swedish krona", flag: "🇸🇪" },
  { code: "SGD", name: "Singapore dollar", flag: "🇸🇬" },
  { code: "SHP", name: "Saint Helena pound", flag: "🇸🇭" },
  { code: "SLE", name: "Sierra Leonean leone", flag: "🇸🇱" },
  { code: "SOS", name: "Somali shilling", flag: "🇸🇴" },
  { code: "SRD", name: "Surinamese dollar", flag: "🇸🇷" },
  { code: "SSP", name: "South Sudanese pound", flag: "🇸🇸" },
  { code: "STN", name: "São Tomé and Príncipe dobra", flag: "🇸🇹" },
  { code: "SYP", name: "Syrian pound", flag: "🇸🇾" },
  { code: "SZL", name: "Eswatini lilangeni", flag: "🇸🇿" },
  { code: "THB", name: "Thai baht", flag: "🇹🇭" },
  { code: "TJS", name: "Tajikistani somoni", flag: "🇹🇯" },
  { code: "TMT", name: "Turkmenistani manat", flag: "🇹🇲" },
  { code: "TND", name: "Tunisian dinar", flag: "🇹🇳" },
  { code: "TOP", name: "Tongan paʻanga", flag: "🇹🇴" },
  { code: "TRY", name: "Turkish lira", flag: "🇹🇷" },
  { code: "TTD", name: "Trinidad and Tobago dollar", flag: "🇹🇹" },
  { code: "TWD", name: "New Taiwan dollar", flag: "🇹🇼" },
  { code: "TZS", name: "Tanzanian shilling", flag: "🇹🇿" },
  { code: "UAH", name: "Ukrainian hryvnia", flag: "🇺🇦" },
  { code: "UGX", name: "Ugandan shilling", flag: "🇺🇬" },
  { code: "USD", name: "US dollar", flag: "🇺🇸" },
  { code: "UYU", name: "Uruguayan peso", flag: "🇺🇾" },
  { code: "UZS", name: "Uzbekistani sum", flag: "🇺🇿" },
  { code: "VES", name: "Venezuelan bolívar", flag: "🇻🇪" },
  { code: "VND", name: "Vietnamese đồng", flag: "🇻🇳" },
  { code: "VUV", name: "Vanuatu vatu", flag: "🇻🇺" },
  { code: "WST", name: "Samoan tālā", flag: "🇼🇸" },
  { code: "XAF", name: "Central African CFA franc", flag: "🇨🇲" },
  { code: "XCD", name: "East Caribbean dollar", flag: "🇦🇬" },
  { code: "XOF", name: "West African CFA franc", flag: "🇸🇳" },
  { code: "XPF", name: "CFP franc", flag: "🇵🇫" },
  { code: "YER", name: "Yemeni rial", flag: "🇾🇪" },
  { code: "ZAR", name: "South African rand", flag: "🇿🇦" },
  { code: "ZMW", name: "Zambian kwacha", flag: "🇿🇲" },
  { code: "ZWL", name: "Zimbabwean dollar", flag: "🇿🇼" },
];

export function findCurrency(code: string): CurrencyInfo | undefined {
  return CURRENCIES.find(c => c.code === code);
}
